package wasmcloud:task-manager;

interface types {
  record operation-error {
    message: string
  }

  record operation {
    id: string,
    original-asset: string,
    created-at: string,

    resized-asset: option<string>,
    resize-error: option<string>,
    resized-at: option<string>,

    analyze-result: option<bool>,
    analyze-error: option<string>,
    analyzed-at: option<string>,
  }
}

interface tracker {
  use types.{operation, operation-error};

  start: func(original-asset: string) -> result<string, operation-error>;

  get: func(
    id: string
  ) -> result<operation, operation-error>;

  complete-resize: func(
    id: string,
    resized-asset: option<string>,
    resize-error: option<string>
  ) -> result<_, operation-error>;

  complete-analyze: func(
    id: string,
    detected: option<bool>,
    analyze-error: option<string>
  ) -> result<_, operation-error>;

  %list: func(
  ) -> result<list<operation>, operation-error>;

  delete: func(
    id: string
  ) -> result<_, operation-error>;
}

world task-manager {
  import wasi:logging/logging;
  import wasmcloud:postgres/query@0.1.0-draft;
  import wasmcloud:postgres/prepared@0.1.0-draft;
  export tracker;
}
